# the port to listen on to handle auth requests
listeningPort: 80

# the list of endpoints to bind to
endpoints:

  # the path to bind to for issuing JWTs
  - path:  /issue
    method: POST
    behavior:  ISSUE

    # specifies the number of hours issued tokens tokens are valid for
    tokenExpiryHours: 2.5

    # specifies whether to repack the POST body as the JWT payload of issued tokens
    usePostBodyForJwtPayload:  false

    # the payload to use for the issued JWT if a POST body is not suplied
    defaultPayload:
      sub: admin
    

  # the endpoint to bind to for verifying JWTS
  - path:  /verify
    method: GET
    behavior:  VERIFY

  # default binding for root; verify the service is working
  - path:  /
    method: GET
    behavior:  RETURN_OK

