# the port to listen on to handle auth requests
listeningPort: 80

# the amount of time issued tokens are valid
tokenExpiryHours: 2.5

# the default payload to use when issuing tokens
defaultPayload:
  sub: "admin"

# the path to bind to for issuing JWTs
# Note:  if found, the body of the HTTP request will
#   be packed into the issued JWT.  Otherwise, the
#   default user will be
issueEndpoint:
  method:  POST
  path:  /issue

# the endpoint to bind to for verifying JWTS
# Note:  the Authorization header is expected to be set
verifyEndpoint:
  method: GET
  path: /verify



